include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "Pipelines/PaM-Info-Nextflow.gitlab-ci.yml"
#

# If your project contains python code, delete the sections below which disable black, isort and flake8
# See also .pre-commit-config.yaml, which will have black, isort and flake8 jobs disabled.

# stop blacks running due to python2 code

black:
  rules:
    - when: never

# isort:
#  rules:
#    - when: never

# flake8:
#   rules:
#    - when: never
#

#     The two sections below prevent this template being deployed to the farm.
#     DELETE THESE SECTIONS THIS IN YOUR PROJECT
# pipeline_deploy_to_farm_test:
#  rules:
#    - when: never

# pipeline_deploy_to_farm_prod:
#  rules:
#    - when: never
#

#     The FARM_NAME variable can be used to set the name of the module on the farm.
#     The module name will be the same as your git project by default.

.pipeline_deploy_to_farm:
  variables:
    FARM_NAME: "Multiple-mappings-to-bam"
#     The check_scan_results job will add up the number of vulnerabilities found in each category (high, medium, etc.)
#     You can set a limit on the number of vulnerabilities that will be tolerated before the job fails; if you need
#     to do this, uncomment the section below and set the limits.  All default to zero.
#     Only set non-zero values if you are unable to fix the vulnerability.  Never do so unless you have updated all
#     dependencies to the most recent version that you can use.  If unsure, seek advice.

#check_scan_results:
#  variables:
#    CRITICAL_LIMIT: 0
#    HIGH_LIMIT: 0
#    MEDIUM_LIMIT: 0
#    LOW_LIMIT: 0
