include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "Pipelines/PaM-Info-Nextflow.gitlab-ci.yml"

# If your project contains python code, delete the sections below which disable black, isort and flake8
# See also .pre-commit-config.yaml, which will have black, isort and flake8 jobs disabled.

black:
  rules:
    - when: never # Else Black errors on the Python2 code

isort:
  rules:
    - when: never

flake8:
  rules:
    - when: never

#     The FARM_NAME variable can be used to set the name of the module on the farm.
#     The module name will be the same as your git project by default.

.pipeline_deploy_to_farm:
  variables:
    FARM_NAME: "multiple-mappings-to-bam"

#     The check_scan_results job will add up the number of vulnerabilities found in each category (high, medium, etc.)
#     You can set a limit on the number of vulnerabilities that will be tolerated before the job fails; if you need
#     to do this, uncomment the section below and set the limits.  All default to zero.
#     Only set non-zero values if you are unable to fix the vulnerability.  Never do so unless you have updated all
#     dependencies to the most recent version that you can use.  If unsure, seek advice.

# The following vulnerabilities cannot be reasonably fixed:
check_scan_results:
  variables:
    CRITICAL_LIMIT: 0
    HIGH_LIMIT: 113 # Command injections, however nothing should be executed that the user can't do anyway
    MEDIUM_LIMIT: 0
    LOW_LIMIT: 12 # Random number generation, though not used here for security but rather intermediate file naming
